version: "3.7"

services:
  carlemany-backend:
    build:
      context: .
      target: carlemany-backend-dev
    image: carlemany-backend-dev
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /carlemany-backend
    ports:
      - "8080:80"  # Changed from 8000:80 to 8080:80
    networks:
      - carlemany-net

  black:
    image: carlemany-backend-dev:latest
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
        read_only: true
    entrypoint: sh -c "black --config .black --check --diff ."

  format:
    image: carlemany-backend-dev:latest
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
    entrypoint: sh -c "black --config .black . && ruff check --fix"

  test:
    image: carlemany-backend-test:latest
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
    networks:
      - carlemany-net

  test-cov:
    image: carlemany-backend-test:latest
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
    entrypoint: pytest --maxfail=10 --cov --cov-report=term --cov-report=html --junitxml=tests/test-results/junit.xml
    networks:
      - carlemany-net

networks:
  carlemany-net: